name: Device Type / Domain
description: You are missing a specific device type / domain?
title: "[Device]: "
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: input
    attributes:
      label: Device type
      description: What type of device are you missing?
    validations:
      required: true
  - type: input
    attributes:
      label: Matter Device
      description: If you already checked the [Matter specification](https://csa-iot.org/developer-resource/specifications-download-request/), please provide the expected device type to use.
  - type: textarea
    attributes:
      label: State and attributes
      description: Please share the state value and attributes of the entity (Home Assistant -> Developer Tools -> States).
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional remarks
      description: If you like to tell us more, feel free to add as much details as you like here.

  - type: checkboxes
    attributes:
      label: "Documentation & Issues"
      options:
        - label: I have reviewed the list of [currently supported entities and their limitations](https://t0bst4r.github.io/home-assistant-matter-hub/supported-device-types).
          required: true
        - label: I have searched the [issues](https://github.com/t0bst4r/home-assistant-matter-hub/issues) for a similar requests.
          required: true
        - label: I have [checked](https://github.com/project-chip/matter.js/blob/main/docs/ECOSYSTEMS.md) if my controller is known to support the requested device type.
          required: true
