name: Pull Request

on:
  pull_request:

permissions:
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: NX cache
        uses: actions/cache@v4
        with:
          path: .nx
          key: ${{ runner.os }}-nx

      - run: npm ci

      - run: npx nx run-many -t lint test build
      - run: npm run prettier
